SELECT * FROM TEST15;
SELECT * FROM TEST16;

--p396 따라하기
SELECT ROWNUM C_NO, F_OBJ
FROM ( SELECT F_OBJ F_OBJ FROM TEST15
UNION 
SELECT T_OBJ F_OBJ FROM TEST15 );

SELECT A.C_NO, B.C_NO AS R_NO, A.F_OBJ, B.F_OBJ AS T_OBJ
FROM 
  ( SELECT ROWNUM C_NO, F_OBJ
    FROM ( SELECT F_OBJ F_OBJ FROM TEST15
    UNION 
    SELECT T_OBJ F_OBJ FROM TEST15 ) ) A,
  ( SELECT ROWNUM C_NO, F_OBJ
    FROM ( SELECT F_OBJ F_OBJ FROM TEST15
    UNION 
    SELECT T_OBJ F_OBJ FROM TEST15 ) ) B;
    
SELECT STRUCTURE.C_NO, STRUCTURE.R_NO, 
       STRUCTURE.F_OBJ, STRUCTURE.T_OBJ, TEST15.VAL
FROM
( SELECT A.C_NO, B.C_NO AS R_NO, A.F_OBJ, B.F_OBJ AS T_OBJ
FROM 
  ( SELECT ROWNUM C_NO, F_OBJ
    FROM ( SELECT F_OBJ F_OBJ FROM TEST15
    UNION 
    SELECT T_OBJ F_OBJ FROM TEST15 ) ) A,
  ( SELECT ROWNUM C_NO, F_OBJ
    FROM ( SELECT F_OBJ F_OBJ FROM TEST15
    UNION 
    SELECT T_OBJ F_OBJ FROM TEST15 ) ) B ) STRUCTURE, 
    TEST15 
WHERE TEST15.F_OBJ (+) = STRUCTURE.F_OBJ 
  AND TEST15.T_OBJ (+) = STRUCTURE.T_OBJ
   