--p429 성명 가져오기 : 자체 풀이
SELECT * FROM T_MANAGER;
SELECT * FROM TEMP;

--서브쿼리 t1 : MAIN_EMP 에 따른 MAIN_NAME 출력
SELECT A.UTILITY, A.MAIN_EMP, B.EMP_NAME AS MAIN_NAME, A.SUB1_EMP, A.SUB2_EMP
FROM T_MANAGER A, TEMP B   -- TEMP 테이블 첫 번째 로딩
WHERE A.MAIN_EMP = B.EMP_ID (+) ;

--서브쿼리 t1 을 TEMP 테이블 t2 와 Outer Join => 서브쿼리 t3
--SUB1_EMP 에 따른 EMP_NAME 을 SUB1_NAME 으로 출력
SELECT T1.*, T2.EMP_NAME AS SUB1_NAME
FROM ( SELECT A.UTILITY, A.MAIN_EMP, B.EMP_NAME AS MAIN_NAME, A.SUB1_EMP, A.SUB2_EMP
          FROM T_MANAGER A, TEMP B   -- TEMP 테이블 두 번째 로딩
          WHERE A.MAIN_EMP = B.EMP_ID (+) ) T1, TEMP T2
WHERE T1.SUB1_EMP = T2.EMP_ID (+);

--다시 서브쿼리 t3 을 TEMP 테이블 t4 와 Outer Join
--SUB2_EMP 에 따른 EMP_NAME 을 SUB_NAME 으로 출력
SELECT T3.*, T4.EMP_NAME AS SUB2_NAME
FROM
( SELECT T1.*, T2.EMP_NAME AS SUB1_NAME
FROM ( SELECT A.UTILITY, A.MAIN_EMP, B.EMP_NAME AS MAIN_NAME, A.SUB1_EMP, A.SUB2_EMP
          FROM T_MANAGER A, TEMP B
          WHERE A.MAIN_EMP = B.EMP_ID (+) ) T1, TEMP T2
WHERE T1.SUB1_EMP = T2.EMP_ID (+) ) T3, TEMP T4  -- TEMP 테이블 세 번째 로딩
WHERE T3.SUB2_EMP = T4.EMP_ID (+);  -- 출력되는 열의 순서는 다름


--책의 풀이 : TEMP 를 세 번 읽어와서 세 번 조인한다
SELECT A.UTILITY, A.MAIN_EMP, B.EMP_NAME, A.SUB1_EMP, C.EMP_NAME, A.SUB2_EMP, D.EMP_NAME
FROM T_MANAGER A, TEMP B, TEMP C, TEMP D
WHERE A.MAIN_EMP = B.EMP_ID
   AND A.SUB1_EMP = C.EMP_ID (+)
   AND A.SUB2_EMP = D.EMP_ID (+);



--p431 문제 20-1 명칭 가져오기
SELECT * FROM TDEPT;
SELECT A.DEPT_CODE, A.DEPT_NAME, A.BOSS_ID, B.EMP_NAME
FROM TDEPT A, TEMP B
WHERE A.BOSS_ID = B.EMP_ID (+);  -- 사장실이 TDEPT 에 없음!!

SELECT * FROM T_MANAGER;
SELECT * FROM TEMP;


--p432 따라하기 : 실습용 코드 추가
INSERT INTO T_MANAGER VALUES ('발전시설', 50000001, NULL, NULL );

SELECT * FROM T_MANAGER;
SELECT * FROM TEMP;
SELECT * FROM TEMP_CON;

SELECT A.UTILITY, A.MAIN_EMP,  
  ( CASE WHEN B.EMP_NAME IS NULL THEN C.EMP_NAME
              ELSE B.EMP_NAME END ) EMD_NAME 
FROM T_MANAGER A, TEMP_CON B, TEMP C 
WHERE A.MAIN_EMP = B.EMP_ID (+)
  AND A.MAIN_EMP = C.EMP_ID (+);  --아우터 조인

SELECT A.UTILITY, A.MAIN_EMP, B.EMP_NAME
FROM
( SELECT * FROM TEMP
  UNION ALL
  SELECT * FROM TEMP_CON ) B, T_MANAGER A
WHERE A.MAIN_EMP = B.EMP_ID (+);   --인라인 뷰

--p435 따라하기 : 차이 비교
INSERT INTO T_MANAGER VALUES ('조명시설', 99999999, NULL, NULL );

SELECT * FROM T_MANAGER;
SELECT * FROM TEMP;
SELECT * FROM TEMP_CON;


--p437 문제 20-2 두 개 이상의 테이블의 Outer Join
SELECT A.UTILITY, A.MAIN_EMP, B.EMP_NAME, 
       A.SUB1_EMP, C.EMP_NAME, 
       A.SUB2_EMP, D.EMP_NAME
FROM T_MANAGER A, 
  ( SELECT * FROM TEMP
    UNION ALL
    SELECT * FROM TEMP_CON ) B, 
  TEMP C, TEMP D
WHERE A.MAIN_EMP = B.EMP_ID (+)
   AND A.SUB1_EMP = C.EMP_ID (+)
   AND A.SUB2_EMP = D.EMP_ID (+)
ORDER BY A.MAIN_EMP;