--20장. 명칭 가져오기 => 테이블에 마지막 2행 추가
SELECT * FROM T_MANAGER;

INSERT INTO T_MANAGER VALUES ('발전시설', 50000001, NULL, NULL );
INSERT INTO T_MANAGER VALUES ('조명시설', 99999999, NULL, NULL );

--실습 전 환경변수 조회
SELECT * FROM v$nls_parameters;

SELECT name, value$
FROM sys.props$
WHERE name = 'NLS_LANGUAGE';

SELECT name, value$
FROM sys.props$
WHERE name = 'NLS_CHARACTERSET';

--p508 따라하기 : CHARACTER SET 확인
SELECT INSTR(UTILITY, '시') I1, INSTRB(UTILITY, '시') I2, 
       INSTR(MAIN_EMP, 4) I3, INSTRB(MAIN_EMP, 4) I4, 
       SUBSTR(UTILITY, 2, 2) S1, SUBSTRB(UTILITY, 2, 2) S2, 
       SUBSTRB(UTILITY, 3, 2) S3, SUBSTRB(UTILITY, 3, 1) S4,
       SUBSTR(MAIN_EMP, 2, 1) S5, SUBSTRB(MAIN_EMP, 2, 1) S6, 
       LENGTH(UTILITY) L1, LENGTHB (UTILITY) L2, 
       LENGTH(MAIN_EMP) L3, LENGTHB( MAIN_EMP) L4
FROM T_MANAGER;

SELECT USERENV('LANGUAGE') FROM DUAL;

--p511 알아두기 : CHARACTER SET 변경
--SYS USER 로그인 후
UPDATE SYS.PROPS$
SET VALUE$ = 'KO16KSC5601'
WHERE NAME = 'NLS_CHARACTERSET';

COMMIT;
-- SYSTEM SHUTDOWN 후 STARTUP




--p512 문제 26-1 : INSTR 과 INSTRB
SELECT * FROM TEST11;

--nls_character 이 AL32UTF8 인 경우 : 한글 한 글자를 3byte
--nls_character 이 AL16UTF16 또는 KO16MSWIN949 인 경우 : 한글 한 글자를 2byte
SELECT DEPT, INSTR(DEPT, '학과')-1, INSTRB(DEPT, '학과')-1 FROM TEST11;




