--p144 문제 04-1
SELECT ROWNUM, CEIL(ROWNUM/3), MOD(ROWNUM,3), 
           DECODE( MOD(ROWNUM,3), 0 , 3 ,MOD(ROWNUM,3) ), 
           EMP_ID, EMP_NAME 
FROM TEMP
ORDER  BY EMP_ID;


--p161 문제 04-2
SELECT CEIL(ROWNUM/3) AS "No", 
           DECODE(MOD(ROWNUM,3),1,EMP_ID,NULL) AS "1st",
           DECODE(MOD(ROWNUM,3),1,EMP_NAME,NULL) AS "2nd",
           DECODE(MOD(ROWNUM,3),2,EMP_ID,NULL) AS "3rd",
           DECODE(MOD(ROWNUM,3),2,EMP_NAME,NULL) AS "4st",
           DECODE(MOD(ROWNUM,3),0,EMP_ID,NULL) AS "5st",
           DECODE(MOD(ROWNUM,3),0,EMP_NAME,NULL) AS "6st"
FROM TEMP
ORDER  BY EMP_ID;

--p163 문제 04-3
SELECT CEIL(ROWNUM/3) AS "No", 
           MAX ( DECODE(MOD(ROWNUM,3),1,EMP_ID,NULL) ) AS "1st",
           MAX ( DECODE(MOD(ROWNUM,3),1,EMP_NAME,NULL) ) AS "2nd",
           MAX ( DECODE(MOD(ROWNUM,3),2,EMP_ID,NULL) ) AS "3rd",
           MAX ( DECODE(MOD(ROWNUM,3),2,EMP_NAME,NULL) ) AS "4st",
           MAX ( DECODE(MOD(ROWNUM,3),0,EMP_ID,NULL) ) AS "5st",
           MAX ( DECODE(MOD(ROWNUM,3),0,EMP_NAME,NULL) ) AS "6st"
FROM ( SELECT * FROM TEMP ORDER BY EMP_ID )
GROUP BY CEIL(ROWNUM/3)
ORDER BY CEIL(ROWNUM/3);

--168 문제 04-4
SELECT *
FROM ( SELECT ROWNUM AS NO, EMP_ID, EMP_NAME FROM TEMP ORDER BY EMP_ID )
WHERE NO BETWEEN 5 AND 10
ORDER BY NO;   
--  내부 테이블을 EMP_ID 로 정렬하지 않을 경우, 출력결과가 달라짐
